import Sidebar from "./Components/Sidebar";
import "./globals.css";

import { Orbit, Roboto_Mono, Inconsolata } from "next/font/google";

const orbit = Orbit({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-orbit",
});

const roboto_mono = Roboto_Mono({
  subsets: ["latin"],
  weight: ["500", "600", "700"],
  variable: "--font-roboto-mono",
});

const inconsolata = Inconsolata({
  subsets: ["latin"],
  weight: ["500", "600", "700"],
  variable: "--font-inconsolata",
});

export const metadata = {
  title: "Lee Jinbok's Portfolio Website",
  description: "Generated by create next.js (v13.4.5) app",
  keywords: ["jinbok", "leejinbok", "진복", "이진복"],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <body
        className={`${orbit.variable} ${inconsolata.variable} ${roboto_mono.variable}`}
      >
        <div>JB</div>
        <div className="layoutContainer">
          <div className="contentsContainer">{children}</div>
          <div className="sidebarContainer">
            <Sidebar />
          </div>
        </div>
      </body>
    </html>
  );
}
